package model;
// Generated 10/12/2017 01:33:24 by Hibernate Tools 4.3.1



/**
 * ParticipaId generated by hbm2java
 */
public class ParticipaId  implements java.io.Serializable {


     private int idTurma;
     private int idAluno;

    public ParticipaId() {
    }

    public ParticipaId(int idTurma, int idAluno) {
       this.idTurma = idTurma;
       this.idAluno = idAluno;
    }
   
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipaId) ) return false;
		 ParticipaId castOther = ( ParticipaId ) other; 
         
		 return (this.getIdTurma()==castOther.getIdTurma())
 && (this.getIdAluno()==castOther.getIdAluno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTurma();
         result = 37 * result + this.getIdAluno();
         return result;
   }   


}


