package model;
// Generated 10/12/2017 01:33:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer idProfessor;
     private String identidade;
     private String email;
     private String senha;
     private byte[] foto;
     private String primeiroNome;
     private String sobrenome;
     private String modalidade;
     private Integer tipoSalario;
     private byte administrador;
     private char sexo;
     private String telefone;
     private byte ativo;
     private byte[] curriculo;
     private Set turmas = new HashSet(0);

    public Professor() {
    }

	
    public Professor(String identidade, String email, String senha, String primeiroNome, String sobrenome, String modalidade, byte administrador, char sexo, String telefone, byte ativo) {
        this.identidade = identidade;
        this.email = email;
        this.senha = senha;
        this.primeiroNome = primeiroNome;
        this.sobrenome = sobrenome;
        this.modalidade = modalidade;
        this.administrador = administrador;
        this.sexo = sexo;
        this.telefone = telefone;
        this.ativo = ativo;
    }
    public Professor(String identidade, String email, String senha, byte[] foto, String primeiroNome, String sobrenome, String modalidade, Integer tipoSalario, byte administrador, char sexo, String telefone, byte ativo, byte[] curriculo, Set turmas) {
       this.identidade = identidade;
       this.email = email;
       this.senha = senha;
       this.foto = foto;
       this.primeiroNome = primeiroNome;
       this.sobrenome = sobrenome;
       this.modalidade = modalidade;
       this.tipoSalario = tipoSalario;
       this.administrador = administrador;
       this.sexo = sexo;
       this.telefone = telefone;
       this.ativo = ativo;
       this.curriculo = curriculo;
       this.turmas = turmas;
    }
   
    public Integer getIdProfessor() {
        return this.idProfessor;
    }
    
    public void setIdProfessor(Integer idProfessor) {
        this.idProfessor = idProfessor;
    }
    public String getIdentidade() {
        return this.identidade;
    }
    
    public void setIdentidade(String identidade) {
        this.identidade = identidade;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getPrimeiroNome() {
        return this.primeiroNome;
    }
    
    public void setPrimeiroNome(String primeiroNome) {
        this.primeiroNome = primeiroNome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getModalidade() {
        return this.modalidade;
    }
    
    public void setModalidade(String modalidade) {
        this.modalidade = modalidade;
    }
    public Integer getTipoSalario() {
        return this.tipoSalario;
    }
    
    public void setTipoSalario(Integer tipoSalario) {
        this.tipoSalario = tipoSalario;
    }
    public byte getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(byte administrador) {
        this.administrador = administrador;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public byte getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(byte ativo) {
        this.ativo = ativo;
    }
    public byte[] getCurriculo() {
        return this.curriculo;
    }
    
    public void setCurriculo(byte[] curriculo) {
        this.curriculo = curriculo;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


