package model;
// Generated 10/12/2017 01:33:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer idTurma;
     private Professor professor;
     private String horario;
     private int maxAlunos;
     private float valoMensalidade;
     private String modalidade;
     private Set participas = new HashSet(0);

    public Turma() {
    }

	
    public Turma(Professor professor, int maxAlunos, float valoMensalidade, String modalidade) {
        this.professor = professor;
        this.maxAlunos = maxAlunos;
        this.valoMensalidade = valoMensalidade;
        this.modalidade = modalidade;
    }
    public Turma(Professor professor, String horario, int maxAlunos, float valoMensalidade, String modalidade, Set participas) {
       this.professor = professor;
       this.horario = horario;
       this.maxAlunos = maxAlunos;
       this.valoMensalidade = valoMensalidade;
       this.modalidade = modalidade;
       this.participas = participas;
    }
   
    public Integer getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(Integer idTurma) {
        this.idTurma = idTurma;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public int getMaxAlunos() {
        return this.maxAlunos;
    }
    
    public void setMaxAlunos(int maxAlunos) {
        this.maxAlunos = maxAlunos;
    }
    public float getValoMensalidade() {
        return this.valoMensalidade;
    }
    
    public void setValoMensalidade(float valoMensalidade) {
        this.valoMensalidade = valoMensalidade;
    }
    public String getModalidade() {
        return this.modalidade;
    }
    
    public void setModalidade(String modalidade) {
        this.modalidade = modalidade;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }




}


